ALTER DATABASE asterisk OWNER TO asterisk;
GRANT ALL PRIVILEGES ON DATABASE asterisk TO asterisk;
GRANT ALL PRIVILEGES ON SCHEMA public TO asterisk;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO asterisk;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO asterisk;
